language: node_js

node_js:
  - "8.9"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

cache:
  yarn: true
  directories:
    - "node_modules"

env:
  - CXX=g++-4.8


