language: node_js
node_js:
- '8.9'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  yarn: true
  directories:
  - node_modules

env:
  matrix:
  - CXX=g++-4.8

  global:
    secure: "ACFJ1ggpgIBRu0Qs0nlG17uq5T8pBOdZAbk9PHrHOpmp+MGyjCgOleafj7cN+aMoWuUTWS3N/M+Au5l0+4KQDPniZW9P6Vb1vyKPyJgIceUxQSTokcowd6vcvQT0SEzNhc/n/yG1LQbhN/ZC1+1tQbJKqBiZtuQNSVgcu015/y7BdVbZb0N8yi7pVYpp9tXARtTZJd+IIpvf2vMm7NiF18ewU6EqL3l5tQ1k4LVC/7R/qJ1b5T8+55/bl6RhYe6128ehl+mcl7zB6KT3B8WaYVWMTzGtd50aWnCt6agWnW3qCCakB4rQy6kd0QHXkVMLSsp/7LWirmNiZZA55cuvjz2DYOSa4ERt/gqvrV848NZIYQQC0me9dIr13OABYTrYff9Iwxk7XcKO4VYoMLzj5Haa87A+lbgpm4hzHXNlXeuNTYnAcRCeVq2Uy04egtvnpHBvMPhE5nqhR/Y8RqwtceiWmxB2MEUGd4oTIC3xGxhC/hqOY6q1GyaUlfiByqkFHy8ESyZIgtu6f9silpcWoL3r9Af8vbhxsza0O5FeYVUJeIiWnZ1mMvqyy4SO43tKvapHDi5IKJ2QkTYgtx688Uh8pgFp8f5A52PBhz/3GvJD3aeUGCcEI0/8Tvm4FR1DmKd3T9aO76p7XU+rmntcKludMSmG6ZASUxgC7Zof/tE="

script:
- yarn test
- yarn code-coverage
